### PR TITLE
Upgrade API Usage, fixing build

### PR DESCRIPTION
**Pull request by alcinnz**
I found that Typograffiti's code was broken against the configured version of the FreeType2 &, to a lesser extent, SDL2 language bindings. This pull request represents the simplest changes to fix the build.

P.S. I'm struggling to get Stack running to completion, so I'm using the Cabal buildfile I found on Hackage. That's not part of this pull request unless you want it.

### CODE REVIEW

**Comment by schell** [comment]
Thank you @alcinnz ! Would you have any interest in co-maintainership? I don't have as much time as I'd like to maintain this library.

**Comment by alcinnz** [comment]
Sure, Typograffiti is very relevant to my crazy ambitions!

**Comment by alcinnz** [comment]
How would you like to coordinate as we co-maintain this project?

---

So you know where I'm coming from in my collaboration: I'm seeking to see how feasable it is to build my own browser engine(s) in Haskell! And making sure it's components are modular enough they can be reused for other projects. So I'd tend to be keen on exposing more low-level APIs I can hook up to a layout engine & FontConfig (Linux's native fontfile-lookup infrastructure), though I'll also make sure to maintain a higher-level API for others to use. Sound good?

Also I'd be keen to improve Typograffiti's handling of non-latinate alphabets. Though I wouldn't *really* know what I'm doing there, so I'm keen to see if I can find a 3rd collaborator to pull in.

---

I've now studied Typograffiti's code, which'll help me co-maintain it & I like to make sure any code I pull in doesn't have any glaring problems anyways.

I did find some issues to report, and to be clear I'm not judging you. I don't know if I'd have done better.

**Comment by schell** [comment]
That all sounds wonderful. I'll make you an admin of the repo and you can keep it here or move it and generally do what you like. Let me know when you're ready to make a release and we'll talk about hackage.

**Comment by alcinnz** [comment]
Cool! We review each other's pull requests?

**Pull request merged**
